name: Build Android APK

on:
  push:
    branches:
      - main  # Hoặc tên branch của bạn

jobs:
  build:
    runs-on: ubuntu-latest  # Chạy trên môi trường Ubuntu

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Lấy mã nguồn từ GitHub

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'  # Cài đặt JDK 11

    - name: Set up Android SDK
      uses: reactivecircus/android-sdk-installer@v1
      with:
        api-level: '30'  # API level Android 11
        build-tools-version: '30.0.3'  # Cài đặt build tools

    - name: Build APK
      run: ./gradlew assembleRelease  # Chạy Gradle để build APK

    - name: Upload APK artifact
      uses: actions/upload-artifact@v2
      with:
        name: apk
        path: app/build/outputs/apk/release/app-release.apk  # Đường dẫn đến APK đã build
