name: Build Android APK

on:
  push:
    branches:
      - main  # Hoặc tên branch bạn sử dụng

jobs:
  build:
    runs-on: ubuntu-22.04  # Sử dụng phiên bản Ubuntu cụ thể

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Lấy mã nguồn từ GitHub

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '11'  # Cài đặt JDK 11

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: 30  # Android API level 30
        build-tools: 30.0.3  # Phiên bản build tools

    - name: Build APK
      run: ./gradlew assembleRelease  # Chạy Gradle để build APK

    - name: Upload APK artifact
      uses: actions/upload-artifact@v3
      with:
        name: apk
        path: app/build/outputs/apk/release/app-release.apk  # Đường dẫn tới file APK đã build
